name: jay_portfolio
description: My personal portfolio website built with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  line_icons: ^2.0.1
  percent_indicator: ^4.2.2
  provider: ^6.1.5
  simple_icons: ^14.6.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/services/
    - assets/projects/